# Generated by Django 2.2.20 on 2021-04-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
