# Generated by Django 2.2.24 on 2021-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20211018_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
    ]
